# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-15 08:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_auto_20170915_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articledetail',
            name='nid',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
